version: "3.7"
services: 
    php:
        build: ./api
        container_name: php-${PROYECT_NAME}
        restart: always
        ports: 
            - ${PHP_PORT}:80
        depends_on: 
            - mysql
        volumes: 
            - ./api/:/var/www/html/api
        env_file: 
            - .env
    mysql:
        image: mysql:5.7
        container_name: mysql-${PROYECT_NAME}
        ports: 
            - ${MYSQL_PORT}:3306
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            TZ: America/Guatemala
        volumes: 
            - ${VOLUMES_MYSQL}:/var/lib/mysql